spring:
  datasource:
    url: jdbc:mysql://localhost:13306/spring-bood-liquibase?useSSL=false&verifyServerCertificate=false&requireSSL=false
    username: spring-bood-liquibase
    password: spring-bood-liquibase
  jpa:
    database-platform: MYSQL
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
liquibase.enabled: true
