spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SBLiquibase?createDatabaseIfNotExist=true&useSSL=false&verifyServerCertificate=false&requireSSL=false
    username: root
    password: root
  jpa:
    database-platform: MYSQL
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
liquibase.enabled: true
